GET http://localhost:8080/teacher
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2023-07-03T142450.200.json

###

GET http://localhost:8080/teacher
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2023-07-03T141754.200.json

###

POST http://localhost:8080/teacher
Content-Length: 144
Content-Type: */*; charset=UTF-8
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

{
    "firstName": "Test",
    "lastName": "Test",
    "phone": "+37254348955",
    "address": "Laki 15-17",
    "email": "test@gmail.com",
  },

<> 2023-07-03T141740.415.json

###

GET http://localhost:8080/teacher
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2023-07-03T141618.200.json

###

POST http://localhost:8080/teacher
Content-Length: 0
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2023-07-03T141553.400.json

###

GET http://localhost:8080/course
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2023-07-02T195034.200.json

###

GET http://localhost:8080/student
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2023-07-02T195022.200.json

###

GET http://localhost:8080/teacher
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2023-07-02T194550.200.json

###

GET http://localhost:8080/teacher
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2023-07-02T194509.200.json

###

GET http://localhost:8080/teacher
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2023-07-02T193904.200.json

###

GET http://localhost:8080/teacher
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2023-07-02T193824.500.json

###

GET http://localhost:8080/teacher
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2023-07-02T193557.500.json

###

GET http://localhost:8080/teacher
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2023-07-02T193531.500.json

###

GET http://localhost:8080/teacher
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2023-07-02T142544.200.json

###

GET http://localhost:8080/course
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2023-07-02T142511.200.json

###

GET http://localhost:8080/student
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2023-07-01T231915.200.json

###

GET http://localhost:8080/student
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2023-07-01T231408.404.json

###

GET http://localhost:8080/course
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2023-07-01T224111.200.json

###

GET http://localhost:8080/teacher
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2023-07-01T184003.200.json

###

GET http://localhost:8080/teacher
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2023-07-01T183723.200.json

###

GET http://localhost:8080/teacher
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2023-07-01T104535.200.json

###

GET http://localhost:8080/teacher
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2023-07-01T104502.200.json

###

GET http://localhost:8080/teacher
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2023-07-01T104321.200.json

###

